In [1]:
import pandas as pd
import matplotlib as plt

In [5]:
file_path = 'Gender Type and Education Level.csv'

initial_df = pd.read_csv(file_path)
initial_df

,Province/Territory,Description,Total,Male,Female,% of Provincial Population,Male %,Female %
0,Newfoundland and Labrador,Total population,510550,250075,260475,100.0,100.0,100.0
1,Newfoundland and Labrador,"Total - Highest certificate, diploma or degree...",433960,211180,222775,100.0,100.0,100.0
2,Newfoundland and Labrador,Master's degree,17150,6990,10165,4.0,3.3,4.6
3,Newfoundland and Labrador,Earned doctorate,2610,1635,975,0.6,0.8,0.4
4,Newfoundland and Labrador,"Total - Highest certificate, diploma or degree...",267785,129445,138340,100.0,100.0,100.0
...,...,...,...,...,...,...,...,...
86,Nunavut,Master's degree,715,310,405,2.9,2.5,3.3
87,Nunavut,Earned doctorate,50,25,25,0.2,0.2,0.2
88,Nunavut,"Total - Highest certificate, diploma or degree...",17060,8590,8475,100.0,100.0,100.0
89,Nunavut,Master's degree,680,300,385,4.0,3.5,4.5
90,Nunavut,Earned doctorate,50,25,20,0.3,0.3,0.2

In [7]:
print(initial_df.iloc[:, 0].unique())

['Newfoundland and Labrador' 'Prince Edward Island' 'Nova Scotia'
 'New Brunswick' 'Quebec' 'Ontario' 'Manitoba' 'Saskatchewan' 'Alberta'
 'British Columbia' 'Yukon' 'Northwest Territories' 'Nunavut']

In [14]:
# Get unique values from the first column
unique_values = initial_df["Province/Territory"].unique()

# Create a dictionary to store DataFrames
dfs_by_province = {}

# Iterate through unique values and create DataFrames
for value in unique_values:
    # Filter the original DataFrame for the current value
    df_province = initial_df[initial_df["Province/Territory"] == value]
    
    # Store the DataFrame in the dictionary
    dfs_by_province[value] = df_province

# dfs_by_province['Newfoundland and Labrador']
dfs_by_province['Prince Edward Island']
# dfs_by_province['Nova Scotia']
# dfs_by_province['New Brunswick']
# dfs_by_province['Quebec']
# dfs_by_province['Ontario']
# dfs_by_province['Manitoba']
# dfs_by_province['Alberta']
# dfs_by_province['British Columbia']
# dfs_by_province['Yukon']
# dfs_by_province['Northwest Territories']
# dfs_by_province['Nunavut']

,Province/Territory,Description,Total,Male,Female,% of Provincial Population,Male %,Female %
7,Prince Edward Island,Total population,154330,75385,78945,100.0,100.0,100.0
8,Prince Edward Island,"Total - Highest certificate, diploma or degree...",126895,61450,65445,100.0,100.0,100.0
9,Prince Edward Island,Master's degree,5930,2465,3465,4.7,4.0,5.3
10,Prince Edward Island,Earned doctorate,800,495,305,0.6,0.8,0.5
11,Prince Edward Island,"Total - Highest certificate, diploma or degree...",77465,37375,40090,100.0,100.0,100.0
12,Prince Edward Island,Master's degree,4685,1795,2890,6.0,4.8,7.2
13,Prince Edward Island,Earned doctorate,595,350,245,0.8,0.9,0.6